config/routes.rb
VdmTracker::Application.routes.draw do

  root 'tracking#new'

  resource(:tracking, controller: :tracking) do
    collection do
      post :search
    end
  end

  

end

app/models/tracker.rb
require 'net/http'
class Tracker

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :tracking_number, :information

  validates :tracking_number, :presence => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def track
    track_fedex(tracking_number)
  end

  def track_fedex tracking_number
    begin
      @fedex ||= Fedex::Shipment.new(key: "e7hchnqJyRbXYuk3",
                               password:"ebHRlMJlq1pC4t6BNnphdmuHI",
                               account_number: "510087321",
                               meter:"100200352",
                               mode: "development")
      self.information = @fedex.track(tracking_number: tracking_number).first

    rescue Exception => e
      errors.add(:tracking_number, e.message)
    end
  end


  def track_dhl tracking_number

    url = URI.parse("http://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=en&idc=217703557591&extendedSearch=true")
    req = Net::HTTP::Get.new(url.path)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }

    puts res.body
   response_html = Nokogiri::HTML(res.body)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracking_controller.rb
class TrackingController < ApplicationController


  def new
    @tracker = Tracker.new
  end

  def search
    @tracker = Tracker.new(params[:tracker])
    if @tracker.valid?
      @tracker.track
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracking_helper.rb
module TrackingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VdmTracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "VdmTracker", new_tracking_path, class: "brand", remote: true  %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Track", new_tracking_path, remote: true  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


      <footer>
        <p>&copy; Company 2014</p>
      </footer>


    </div> <!-- /container -->
    <%= render partial: "shared/transition" %>
    <div id="emptyContainer">

    </div>

  </body>
</html>

app/views/shared/_transition.html.erb
<div class="transition hide"><%= image_tag "loaderBG.gif" %></div>

app/views/tracking/_form.html.erb
<%= simple_form_for @tracker,url: search_tracking_path, remote: true ,class: "form-horizontal" do |f| %>
    <fieldset>

      <!-- Form Name -->
      <legend>Track your package</legend>

      <!-- Text input-->
      <%= f.input :tracking_number, placeholder: "Tracking number", class: "input-xlarge" %>

      <!-- Button -->
      <div class="control-group">
        <label class="control-label" for="singlebutton"></label>
        <div class="controls">
          <button id="singlebutton" name="singlebutton" class="btn btn-primary">Search</button>
        </div>
      </div>

    </fieldset>
<% end %>

app/views/tracking/_new.html.erb
<div class="modal fade" id='trackerModal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%=render partial: "form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<script>
  $(function(){
      $("#trackerModal").modal();
  });
</script>

app/views/tracking/_result.html.erb
<h3>Tracking Id: <%= tracking_information.tracking_number %></h3>


<div class="table-responsive table-striped table-hover">
  <table class="table">
    <% tracking_information.details.each do |key, value| %>
        <% if value.is_a?(String) %>
            <tr>
              <td>
                <b><%= key.to_s.titleize %></b>
              </td>
              <td>
                <%= value.titleize %>
              </td>
            </tr>
        <% end %>
    <% end %>
  </table>
</div>


<br/>

<%= link_to new_tracking_path, remote: true, class: "btn btn-sm btn-info" do %>
    <span class="glyphicon glyphicon-circle-arrow-left"></span> Back To Search
<% end %>

<script>
    $(function(){
        $("#trackerModal").modal("hide");
    });
</script>

app/views/tracking/new.html.erb
<div id="content-holder">
    <%= render partial: "tracking/form" %>
</div>

app/views/tracking/new.js.erb
$("#content-holder").html("<%= escape_javascript(render partial: "tracking/form") %>")

app/views/tracking/search.js.erb
<% unless @tracker.errors.any? %>
    $("#content-holder").html("<%= escape_javascript(render partial: "result", locals: {tracking_information: @tracker.information}) %>")
<% else %>
    emptyContainer.html("<%= escape_javascript(render partial: "new") %>");
<% end %>